packages:
  - "apps/*"
  - "packages/*"
catalog:
  '@ai-sdk/anthropic': ^4.0.49
  '@ai-sdk/deepseek': ^3.0.39
  '@ai-sdk/google': ^4.0.64
  '@ai-sdk/mistral': ^4.0.39
  '@ai-sdk/openai': ^4.0.60
  '@openrouter/ai-sdk-provider': ^3.0.0
  ai: ^7.0.93
allowBuilds:
  '@clerk/shared': false
  esbuild: false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.53 || 4.0.74'
  - '@ai-sdk/google@4.0.45'
  - ai@7.0.67 || 7.0.92
overrides:
  fast-uri: 3.1.6
  prismjs: '>=1.30.0'
  qs: 6.16.0
  uuid: '>=11.1.1'

# apps/** packages/** means "all subdirectories" resulting in next error. Once an app has built, your workspace declaration is picking up apps/docs/.next as a workspace.
